from zdrowadieta.models import *
import datetime 

user = MainUser.objects.create_user(username = 'jKowalski', password = 'Kowalski123')
new_user1 = User(user = user, isAdmin = True, isDietician = False)
new_user1.save()
new_client1 = Client(user = new_user1, name = 'Jan', last_name = 'Kowalski', weight = 85, height = 175, age = 44)
new_client1.save()


user = MainUser.objects.create_user(username = 'mZalewski', password = 'Zalewski123')
new_user2 = User(user = user, isAdmin = False, isDietician = True)
new_user2.save()
new_dietician1 = Dietician(user = new_user2, name = 'Mateusz', last_name = 'Zalewski')
new_dietician1.save()


user = MainUser.objects.create_user(username = 'kKaczmarczyk', password = 'Kaczmarczyk123')
new_user3 = User(user = user, isAdmin = False, isDietician = False)
new_user3.save()
new_client2 = Client(user = new_user3, name = 'Kamil', last_name = 'Kaczmarczyk', weight = 105, height = 172, age = 59)
new_client2.save()


new_disease1 = Disease(name = 'Cukrzyca typu 1')
new_disease1.save()
new_disease2 = Disease(name = 'Cukrzyca typu 2')
new_disease2.save()


new_user_disease = UserDisease(user = new_user1, disease = new_disease1)
new_user_disease.save()
new_user_disease = UserDisease(user = new_user2, disease = new_disease2)
new_user_disease.save()
new_user_disease = UserDisease(user = new_user3, disease = new_disease1)
new_user_disease.save()
new_user_disease = UserDisease(user = new_user2, disease = new_disease2)
new_user_disease.save()
new_user_disease = UserDisease(user = new_user2, disease = new_disease2)
new_user_disease.save()
new_user_disease = UserDisease(user = new_user2, disease = new_disease2)
new_user_disease.save()


new_ingredient1 = Ingredient(name = 'Ser żółty', calories = 225, proteins= 24.9, fats = 27.4, carbs = 2.22)
new_ingredient1.save()
new_ingredient2 = Ingredient(name = 'Ogórek', calories = 56, proteins= 5.73, fats = 0.18, carbs = 7.68)
new_ingredient2.save()
new_ingredient3 = Ingredient(name = 'Kurczak', calories = 158, proteins= 18.6, fats = 9.3, carbs = 0.0)
new_ingredient3.save()
new_ingredient4 = Ingredient(name = 'Kalafior', calories = 25, proteins= 1.92, fats = 0.28, carbs = 4.97)
new_ingredient4.save()
new_ingredient5 = Ingredient(name = 'Łosoś', calories = 159, proteins = 18.4, fats = 7.5, carbs = 4.5)
new_ingredient5.save()
new_ingredient6 = Ingredient(name = 'Platki owsiane', calories = 366, proteins= 13.15, fats = 6.52, carbs = 67.7)
new_ingredient6.save()
new_ingredient7 = Ingredient(name = 'Jogurt naturalny', calories = 56, proteins = 5.73, fats = 0.18, carbs = 7.68)
new_ingredient7.save()
new_ingredient8 = Ingredient(name = 'Pomarańcz', calories = 47, proteins = 0.94, fats = 0.12, carbs = 11.75)
new_ingredient8.save()
new_ingredient9 = Ingredient(name = 'Orzechy nerkowca', calories = 533, proteins = 18.22, fats = 43.85, carbs = 30.19)
new_ingredient9.save()
new_ingredient10 = Ingredient(name = 'Pieczywo żytnie', calories = 225, proteins = 6.8, fats = 1.8, carbs = 44.7)
new_ingredient10.save()
new_ingredient11 = Ingredient(name = 'Masło', calories = 744, proteins = 0.63, fats = 82.38, carbs = 0.7)
new_ingredient11.save()
new_ingredient12 = Ingredient(name = 'Wędlina drobiowa', calories = 126, proteins = 17.89, fats = 4.98, carbs = 1.43)
new_ingredient12.save()
new_ingredient13 = Ingredient(name = 'Pomidor', calories = 18, proteins = 0.88, fats = 0.2, carbs = 3.89)
new_ingredient13.save()
new_ingredient14 = Ingredient(name = 'Sałata', calories = 14, proteins = 0.9, fats = 0.14, carbs = 2.97)
new_ingredient14.save()
new_ingredient15 = Ingredient(name = 'Brokuł', calories = 34, proteins = 2.82, fats = 0.37, carbs = 6.64)
new_ingredient15.save()
new_ingredient16 = Ingredient(name = 'Fasolka szparagowa', calories = 345, proteins = 22.0, fats = 2.6, carbs = 60.7)
new_ingredient16.save()
new_ingredient17 = Ingredient(name = 'Marchew', calories = 36, proteins = 0.78, fats = 0.46, carbs = 7.9)
new_ingredient17.save()
new_ingredient18 = Ingredient(name = 'Orzechy włoskie', calories = 654, proteins = 15.23, fats = 65.2, carbs = 13.71)
new_ingredient18.save()
new_ingredient19 = Ingredient(name = 'Jabłko', calories = 52, proteins = 0.26, fats = 0.17, carbs = 13.81)
new_ingredient19.save()
new_ingredient20 = Ingredient(name = 'Serek wiejski', calories = 97, proteins = 11.0, fats = 5.0, carbs = 2.0)
new_ingredient20.save()
new_ingredient21 = Ingredient(name = 'Szczypiorek', calories = 27, proteins = 0.97, fats = 0.47, carbs = 5.74)
new_ingredient21.save()
new_ingredient22 = Ingredient(name = 'Szpinak', calories = 469, proteins = 20.3, fats = 7.7, carbs = 83.9)
new_ingredient22.save()
new_ingredient23 = Ingredient(name = 'Awokado', calories = 168, proteins = 2.0, fats = 15.0, carbs = 4.0)
new_ingredient23.save()
new_ingredient24 = Ingredient(name = 'Słonecznik', calories = 584, proteins = 20.78, fats = 51.46, carbs = 20.0)
new_ingredient24.save()
new_ingredient25 = Ingredient(name = 'Oliwa z oliwek', calories = 884, proteins = 0.0, fats = 100.0, carbs = 0.0)
new_ingredient25.save()
new_ingredient26 = Ingredient(name = 'Jajka', calories = 155, proteins = 12.58, fats = 10.6, carbs = 1.12)
new_ingredient26.save()

new_allergen = Allergen(name = 'Gluten')
new_allergen.save()
new_allergen = Allergen(name = 'Jaja')
new_allergen.save()

new_recipe1 = Recipe(name = 'Owsianka z pomarańczą', method = 'Płatki owsiane zalać wrzątkiem i przykryć talerzykiem. Po chwili dodać jogurt, orzechy i pokrojoną pomarańcze.', calories = 200, type = 'sniadanie')
new_recipe1.save()
new_recipe2 = Recipe(name = 'Kanapka z wędliną', method = 'Bułkę przekroić, posmarować masłem oraz położyć przygotowane składniki.', calories = 200, type = 'II sniadanie')
new_recipe2.save()
new_recipe3 = Recipe(name = 'Łosoś pieczony', method = 'Rybę doprawić solą i pieprzem. Wstawić do nagrzanego do 180 stopni piekarnika i piec przez 25 minut. Fasolkę szparagową gotować w osolonej wodzie 12 minut. Podawać z pokrojonym pomidorem.', calories = 250, type = 'obiad')
new_recipe3.save()
new_recipe4 = Recipe(name = 'Surowa marchewka', method = 'Marchwekę obrać i pokroić.', calories = 200, type = 'podwieczorek')
new_recipe4.save()
new_recipe5 = Recipe(name = 'Serek wiejski z pomidorem i szczypiorkiem', method = '* Do serka wiejskiego dodać drobno pokrojonego pomidora oraz szczypiorek. Doprawić solą i pieprzem do smaku.', calories = 300, type = 'kolacja')
new_recipe5.save()

new_recipe6 = Recipe(name = 'Jajecznica na maśle', method = 'Rozpuścić masło na patelni, wbić jaja i wymieszać. Podawać z pieczywem i pokrojonym pomidorem.', calories = 250, type = 'obiad')
new_recipe6.save()
new_recipe7 = Recipe(name = 'Kanapka z serem', method = 'ułkę przekroić, posmarować masłem oraz położyć przygotowane składniki.', calories = 200, type = 'II sniadanie')
new_recipe7.save()
new_recipe8 = Recipe(name = 'Kurczak pieczony', method = 'Mięso doprawić solą oraz suszoną papryką, piec w piekarniku w 190 stopniach przez 1,5 godziny. Umyty i pokrojony brokuł gotować w posolonej wodzie przez 12 minut.', calories = 250, type = 'obiad')
new_recipe8.save()
new_recipe9 = Recipe(name = 'Garść orzechów włoskich, jabłko', method = '', calories = 200, type = 'podwieczorek')
new_recipe9.save()
new_recipe10 = Recipe(name = 'Sałatka ze szpinaku', method = 'Sałatka ze szpinaku, pomidora, awokado, ze słonecznikiem i oliwą.', calories = 300, type = 'kolacja')
new_recipe10.save()

new_recipeIngredient1 = RecipeIngredient(ingredient = new_ingredient8,recipe = new_recipe1, massFraction = 0.4)
new_recipeIngredient1.save()
new_recipeIngredient2 = RecipeIngredient(ingredient = new_ingredient6,recipe = new_recipe1,massFraction = 0.2)
new_recipeIngredient2.save()
new_recipeIngredient3 = RecipeIngredient(ingredient = new_ingredient7,recipe = new_recipe1,massFraction = 0.4)
new_recipeIngredient3.save()
new_recipeIngredient4 = RecipeIngredient(ingredient = new_ingredient10,recipe = new_recipe2,massFraction = 0.2)
new_recipeIngredient4.save()
new_recipeIngredient5 = RecipeIngredient(ingredient = new_ingredient11,recipe = new_recipe2,massFraction = 0.2)
new_recipeIngredient5.save()
new_recipeIngredient6 = RecipeIngredient(ingredient = new_ingredient12,recipe = new_recipe2,massFraction = 0.2)
new_recipeIngredient6.save()
new_recipeIngredient7 = RecipeIngredient(ingredient = new_ingredient13,recipe = new_recipe2,massFraction = 0.2)
new_recipeIngredient7.save()
new_recipeIngredient8 = RecipeIngredient(ingredient = new_ingredient14,recipe = new_recipe2, massFraction = 0.4)
new_recipeIngredient8.save()
new_recipeIngredient9 = RecipeIngredient(ingredient = new_ingredient5,recipe = new_recipe3,massFraction = 0.4)
new_recipeIngredient9.save()
new_recipeIngredient10 = RecipeIngredient(ingredient = new_ingredient13,recipe = new_recipe3,massFraction = 0.4)
new_recipeIngredient10.save()
new_recipeIngredient11 = RecipeIngredient(ingredient = new_ingredient16,recipe = new_recipe3,massFraction = 0.2)
new_recipeIngredient11.save()
new_recipeIngredient12 = RecipeIngredient(ingredient = new_ingredient17,recipe = new_recipe4,massFraction = 1.0)
new_recipeIngredient12.save()
new_recipeIngredient13 = RecipeIngredient(ingredient = new_ingredient20,recipe = new_recipe5,massFraction = 0.5)
new_recipeIngredient13.save()
new_recipeIngredient14 = RecipeIngredient(ingredient = new_ingredient13,recipe = new_recipe5,massFraction = 0.4)
new_recipeIngredient14.save()
new_recipeIngredient15 = RecipeIngredient(ingredient = new_ingredient21,recipe = new_recipe5, massFraction = 0.1)
new_recipeIngredient15.save()

new_recipeIngredient16 = RecipeIngredient(ingredient = new_ingredient10,recipe = new_recipe6,massFraction = 0.2)
new_recipeIngredient16.save()
new_recipeIngredient17 = RecipeIngredient(ingredient = new_ingredient11,recipe = new_recipe6,massFraction = 0.2)
new_recipeIngredient17.save()
new_recipeIngredient18 = RecipeIngredient(ingredient = new_ingredient26,recipe = new_recipe6,massFraction = 0.4)
new_recipeIngredient18.save()
new_recipeIngredient19 = RecipeIngredient(ingredient = new_ingredient13,recipe = new_recipe6,massFraction = 0.2)
new_recipeIngredient19.save()

new_recipeIngredient22 = RecipeIngredient(ingredient = new_ingredient11,recipe = new_recipe7,massFraction = 0.2)
new_recipeIngredient22.save()
new_recipeIngredient23 = RecipeIngredient(ingredient = new_ingredient1,recipe = new_recipe7,massFraction = 0.2)
new_recipeIngredient23.save()
new_recipeIngredient24 = RecipeIngredient(ingredient = new_ingredient13,recipe = new_recipe7,massFraction = 0.2)
new_recipeIngredient24.save()
new_recipeIngredient25 = RecipeIngredient(ingredient = new_ingredient14,recipe = new_recipe7, massFraction = 0.4)
new_recipeIngredient25.save()

new_recipeIngredient26 = RecipeIngredient(ingredient = new_ingredient3,recipe = new_recipe8,massFraction = 0.5)
new_recipeIngredient26.save()
new_recipeIngredient27 = RecipeIngredient(ingredient = new_ingredient15,recipe = new_recipe8,massFraction = 0.5)
new_recipeIngredient27.save()
new_recipeIngredient28 = RecipeIngredient(ingredient = new_ingredient18,recipe = new_recipe9,massFraction = 0.4)
new_recipeIngredient28.save()
new_recipeIngredient29 = RecipeIngredient(ingredient = new_ingredient19,recipe = new_recipe9, massFraction = 0.6)
new_recipeIngredient29.save()

new_recipeIngredient30 = RecipeIngredient(ingredient = new_ingredient23,recipe = new_recipe10,massFraction = 0.2)
new_recipeIngredient30.save()
new_recipeIngredient31 = RecipeIngredient(ingredient = new_ingredient24,recipe = new_recipe10,massFraction = 0.2)
new_recipeIngredient31.save()
new_recipeIngredient32 = RecipeIngredient(ingredient = new_ingredient25,recipe = new_recipe10,massFraction = 0.2)
new_recipeIngredient32.save()
new_recipeIngredient33 = RecipeIngredient(ingredient = new_ingredient22,recipe = new_recipe10, massFraction = 0.2)
new_recipeIngredient33.save()
new_recipeIngredient34 = RecipeIngredient(ingredient = new_ingredient13,recipe = new_recipe10, massFraction = 0.2)
new_recipeIngredient34.save()

new_menu = Menu(date_from = datetime.date(2020, 10, 12), date_to = datetime.date(2020, 10, 19), calories = 1000)
new_menu.save()

new_client_menu = ClientMenu(client = new_client1, menu = new_menu)
new_client_menu.save()

new_meal1 = Meal(menu = new_menu, recipe = new_recipe1, calories = 300, date = datetime.date(2020, 10, 12))
new_meal1.save()
new_meal2 = Meal(menu = new_menu, recipe = new_recipe2, calories = 350, date = datetime.date(2020, 10, 12))
new_meal2.save()
new_meal3 = Meal(menu = new_menu, recipe = new_recipe3, calories = 270, date = datetime.date(2020, 10, 12))
new_meal3.save()
new_meal4 = Meal(menu = new_menu, recipe = new_recipe4, calories = 400, date = datetime.date(2020, 10, 12))
new_meal4.save()
new_meal5 = Meal(menu = new_menu, recipe = new_recipe5, calories = 350, date = datetime.date(2020, 10, 12))
new_meal5.save()

new_meal6 = Meal(menu = new_menu, recipe = new_recipe6, calories = 200, date = datetime.date(2020, 10, 13))
new_meal6.save()
new_meal7 = Meal(menu = new_menu, recipe = new_recipe7, calories = 450, date = datetime.date(2020, 10, 13))
new_meal7.save()
new_meal8 = Meal(menu = new_menu, recipe = new_recipe8, calories = 170, date = datetime.date(2020, 10, 13))
new_meal8.save()
new_meal9 = Meal(menu = new_menu, recipe = new_recipe9, calories = 300, date = datetime.date(2020, 10, 13))
new_meal9.save()
new_meal10 = Meal(menu = new_menu, recipe = new_recipe10, calories = 250, date = datetime.date(2020, 10, 13))
new_meal10.save()

