# Generated by Django 2.2.3 on 2020-09-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zdrowadieta', '0007_preferredingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Age'),
        ),
    ]
