# Generated by Django 2.2.3 on 2020-09-13 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zdrowadieta', '0012_remove_user_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferredingredient',
            name='ingredient',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='proteins',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Proteins'),
        ),
        migrations.CreateModel(
            name='ClientMenu',
            fields=[
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='zdrowadieta.Menu')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zdrowadieta.Client')),
            ],
        ),
    ]
