# Generated by Django 2.2.3 on 2020-09-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zdrowadieta', '0014_auto_20200914_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(default=0, verbose_name='Calories'),
        ),
    ]
