# Generated by Django 2.2.3 on 2020-09-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zdrowadieta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
