# Generated by Django 2.2.3 on 2020-09-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zdrowadieta', '0003_auto_20200909_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
