# Generated by Django 2.2.3 on 2020-09-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zdrowadieta', '0004_auto_20200909_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Yuriy', max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Kis', max_length=30, verbose_name='Last Name'),
        ),
    ]
