# Generated by Django 2.2.3 on 2020-09-10 18:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zdrowadieta', '0005_auto_20200909_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='zdrowadieta.User')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('last_name', models.CharField(default='', max_length=255, verbose_name='Last Name')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Weight')),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Height')),
            ],
        ),
        migrations.CreateModel(
            name='Dietician',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='zdrowadieta.User')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('last_name', models.CharField(default='', max_length=255, verbose_name='Last Name')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('calories', models.IntegerField(default=0, verbose_name='Calories')),
                ('proteins', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Proteins')),
                ('fats', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Fats')),
                ('carbs', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Carbs')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(default=datetime.date.today, verbose_name='Name')),
                ('date_to', models.DateField(default=datetime.date.today, verbose_name='Name')),
                ('calories', models.IntegerField(default=0, verbose_name='Calories')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('method', models.TextField(default='', verbose_name='Method')),
                ('calories', models.IntegerField(default=0, verbose_name='Calories')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False, verbose_name='IsAdmin'),
        ),
        migrations.AddField(
            model_name='user',
            name='isDietician',
            field=models.BooleanField(default=False, verbose_name='IsDietician'),
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default='', max_length=50, verbose_name='Login'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=255, verbose_name='Password'),
        ),
        migrations.CreateModel(
            name='UserDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zdrowadieta.Disease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zdrowadieta.User')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Weight')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zdrowadieta.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zdrowadieta.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='MenuRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Name')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zdrowadieta.Menu')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zdrowadieta.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientAllergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zdrowadieta.Allergen')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zdrowadieta.Ingredient')),
            ],
        ),
    ]
