# Generated by Django 2.2.3 on 2020-10-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zdrowadieta', '0016_auto_20200914_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(default='', max_length=255, verbose_name='Gender'),
        ),
    ]
