# Generated by Django 2.2.3 on 2020-11-07 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zdrowadieta', '0017_client_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferredingredient',
            name='ingredient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zdrowadieta.Ingredient'),
        ),
        migrations.CreateModel(
            name='StandardClientIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zdrowadieta.Client')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zdrowadieta.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='ClientAllergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zdrowadieta.Allergen')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zdrowadieta.Client')),
            ],
        ),
    ]
