# Generated by Django 2.2.3 on 2020-11-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zdrowadieta', '0018_auto_20201107_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_eaten',
            field=models.BooleanField(default=False),
        ),
    ]
